config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signin", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
  post "/rides/new", to: "rides#new"
  resources :attractions
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  has_many :rides
  has_many :users, :through => :rides
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  belongs_to :attraction

  def take_ride
    enough_tickets, tall_enough = meet_requirements
    if enough_tickets && tall_enough
      start_ride
    elsif tall_enough && !enough_tickets
      "Sorry. " + ticket_issue
    elsif enough_tickets && !tall_enough
      "Sorry. " + height_issue
    else
      "Sorry. " + ticket_issue + " " + height_issue
    end
  end

  def meet_requirements
    enough_tickets, tall_enough = false
    if self.user.tickets >= self.attraction.tickets
      enough_tickets = true
    end
    if self.user.height >= self.attraction.min_height
      tall_enough = true
    end
    return [enough_tickets, tall_enough]
  end

  def start_ride
    new_happiness = self.user.happiness + self.attraction.happiness_rating
    new_nausea = self.user.nausea + self.attraction.nausea_rating
    new_tickets =  self.user.tickets - self.attraction.tickets
    self.user.update(
      :happiness => new_happiness,
      :nausea => new_nausea,
      :tickets => new_tickets
    )
    "Thanks for riding the #{self.attraction.name}!"
  end

  def ticket_issue
    "You do not have enough tickets the #{self.attraction.name}."
  end

  def height_issue
    "You are not tall enough to ride the #{self.attraction.name}."
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :rides
  has_many :attractions, :through => :rides

  def mood
    if self.happiness && self.nausea
      mood = self.happiness - self.nausea
      mood > 0 ? "happy" : "sad"
    end
  end

  def num_of_rides
    self.attractions.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  before_action :require_logged_in, except: [:new, :create, :home]

  def logged_in?
    !!current_user
  end

  private
    def require_logged_in
      redirect_to root_path unless logged_in?
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  def index
    @attractions = Attraction.all
  end

  def show
    @ride = Ride.new
  end

  def new
    @attraction = Attraction.new
  end

  def edit
  end

  def create
    @attraction = Attraction.new(attraction_params)
    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
    end
  end

  private
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    def attraction_params
      params.require(:attraction).permit(
        :name,
        :min_height,
        :tickets,
        :happiness_rating,
        :nausea_rating
      )
    end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  def new
    @ride = Ride.create(
      :user_id => params[:user_id],
      :attraction_id => params[:attraction_id]
    )
    @message = @ride.take_ride
    redirect_to user_path(@ride.user, :message => @message)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def new
    @user = User.new
    @users = User.all
  end

  def create
    @user = User.find_by(name: params[:user][:name])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Welcome back to the theme park!"
    else
      redirect_to signin_path
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @message = params[:message] if params[:message]
    @message ||= false
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to user_path(@user), notice: "Welcome to the theme park!" }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name,
        :password,
        :height,
        :tickets,
        :happiness,
        :nausea,
        :admin
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :min_height, "Height Requirement (in inches)" %><br>
    <%= f.number_field :min_height, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :happiness_rating, "How fun is it? (1-5 scale)" %><br>
    <%= f.number_field :happiness_rating, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :nausea_rating, "How nausea-inducing is it? (1-5 scale)" %><br>
    <%= f.number_field :nausea_rating, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :tickets, "How many tickets does it cost?" %><br>
    <%= f.number_field :tickets, class: "form-control" %></div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<h1>Listing attractions</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr> 
      <td><strong>Name</strong></td>
      <td><strong>Tickets</strong></td>
      <td><strong>Details</strong></td>
    </tr>
    <% @attractions.each do |attraction| %>
      <tr>

        <td><%= attraction.name %></td>
        <td><%= attraction.tickets %></td>
        <% if current_user.admin %>
          <td><%= link_to "Show #{attraction.name}", attraction_path(attraction) %></td>
        <% else %>
          <td><%= link_to "Go on #{attraction.name}", attraction_path(attraction) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if @user %>
  <p>
    <%= link_to "Back to profile", user_path(@user), {:class => "btn btn-primary"} %>
  </p>
<% else %>
  <p><%= link_to 'New Attraction', new_attraction_path %></p>
<% end %>

app/views/attractions/new.html.erb
<h1>New attraction</h1>

<%= render 'form' %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center">

  <div class="info">
    <p><strong>Name:</strong> <%= @attraction.name %></p>
    <p><strong>Total Number of Users:</strong> <%= @attraction.users.count %></p>
    <p><strong>Ticket Requirement:</strong> <%= @attraction.tickets %></p>
    <p><strong>Height Requirement:</strong> <%= @attraction.min_height %> inches</p>
    <p><strong>Nausea Rating:</strong> <%= @attraction.nausea_rating %></p>
    <p><strong>Happiness Rating:</strong> <%= @attraction.happiness_rating %></p>
    <% if current_user.admin %>
      <%= link_to 'Edit Attraction', [:edit, @attraction] %></p>
    <% else %>
      <form action="/rides/new" method="post">
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
        <%= tag(:input, :type => "hidden", :name => :user_id, :value => current_user.id) %>
        <%= tag(:input, :type => "hidden", :name => :attraction_id, :value => @attraction.id) %>
        <input class="btn btn-light" type="submit" value="Go on this ride">
      </form>
    <% end %>
    <%= link_to 'Back', attractions_path,class: "btn btn-primary btn-light" %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAmusementPark</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to "Hello, #{current_user.name}!", user_path(current_user) %></li>
              <li><%= link_to "Attractions", attractions_path %></li>
              <li><%= link_to "Log Out", signout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_path %></li>
              <li><%= link_to "Sign In", signin_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="theme-showcase" role="main">

  <div class="left-pic">
    <img src="http://www.washingtonpost.com/wp-srv/special/health/why-roller-coasters-make-us-scream/images/rollercoasterBackground.jpg" width="550" height="325">
  </div>

  <div class="right-info">
    <h1>Welcome to the Amusement Park!</h1>
    <div class="center">
      <%= link_to "Sign In", signin_path, class: "btn btn-primary" %>
      <%= link_to "Sign Up", new_user_path, class: "btn btn-primary" %>
    </div>
  </div>

</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :height, "Height (in inches)" %>
    <br>
    <%= f.number_field :height, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :happiness, "How happy are you? (1-5 scale)" %>
    <br>
    <%= f.number_field :happiness, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nausea, "How nauseous are you? (1-5 scale)" %>
    <br>
    <%= f.number_field :nausea, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tickets, "How many dollars are in your pocket?" %>
    <br>
    <%= f.number_field :tickets, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :admin, "Check box if you are a theme park owner" %>
    <%= f.check_box :admin, class: "form-check-input" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password, class: "form-control" %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @message %>
  <div class="center alert">
    <p><%= @message %></p>
  </div>
<% end %>

<div class="center">

  <div class="info">
    <% if @user.admin %>
      <p><strong>ADMIN</strong></p>
    <% end %>
    <p><strong>Name:</strong> <%= @user.name %></p>
    <p><strong>Tickets:</strong> <%= @user.tickets %></p>
    <p><strong>Mood:</strong>  <%= @user.mood %></p>
    <p><strong>Height:</strong> <%= @user.height %> inches</p>
    <p><%= link_to 'Edit', edit_user_path(@user) %></p>
    <p><%= link_to 'See attractions', attractions_path %></p>
  </div>
</div>

app/views/users/signin.html.erb
<%= form_for @user, url: "/users/login" do |f| %>

  <div class="field"><%= f.label :name, "Select your name" %><br>
    <%= f.collection_select(:id, @users, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit "Sign In"  %>
  </div>
<% end %>